name: image_viewer
description: Simple pure dart image viewer for use in Flutter apps.
version: 0.2.0
homepage: https://omegadesign.no
repository: https://github.com/Omega-Design-AS/package-image-viewer
publish_to: https://flutter-packages.appframe.com:4242

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: